### ISSUE TITLE
LoafWallet v1.1

### ISSUE THREAD

**Issue by losh11** [litecoin-foundation/LoafWallet#9]
# LoafWallet v1.1

Just generally stuff that's needs to be completed for v1.1. Some things ignored for v1.0 due to lack of time, and work not finished on master/vosine. 

**TODO:**
- [x] Testnet Fee System
- [ ] Difficulty re-calculation
- [x] Buy Litecoin (+ Coinbase)
- [ ] Notification Centre Ticker

**iOS 10 Changes** - _also work on this for master/vosine:_
- [ ] SiriKit transactions
- [ ] iMessage sending transactions

**Comment by briannyeko** [comment]
will you guys offer a widget on ios/android devices (similar to winkdex app) that shows LTC/USD,LTC/BTC or LTC/CNY price?

**Comment by losh11** [comment]
@briannyeko By widget do you mean notification centre item for iOS? Then sure, we could do price conversion alongside the send and receive items we currently have.

![Imgur](http://i.imgur.com/nkMu14l.png)

That's what we currently have ^^.

**Comment by briannyeko** [comment]
This is nice :) sure do it, it would be a great update to the wallet!!!

**Comment by losh11** [comment]
Add loading icon behind webView whilst initially loading. UIWebViews are still very slow.
v1.0.3 release?

**Comment by losh11** [comment]
Closing for release of LoafWallet v2.
